#cloud-config

package_update: true
package_upgrade: false
packages: [curl, build-essential]

runcmd:
  - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
  - apt-get install -y nodejs && npm install -g pm2
  - mkdir -p /opt/services
  - |
    cat > /opt/services/ports.js << 'JSEOF'
    const http = require('http');
    const BIND_IP = process.env.BIND_IP || '0.0.0.0';
    const ports = [3306, 5432, 6379, 8080, 8888, 9200, 27017];

    ports.forEach(port => {
      http.createServer((req, res) => {
        res.writeHead(200, { 'Content-Type': 'text/plain' });
        res.end(`Port ${port} is open`);
      }).listen(port, BIND_IP, () => console.log(`Listening on ${BIND_IP}:${port}`));
    });
    JSEOF
  - |
    PRIVATE_IP=$(curl -s http://169.254.169.254/metadata/v1/interfaces/private/0/ipv4/address)
    cd /opt/services && BIND_IP=${PRIVATE_IP} pm2 start ports.js --name "ports"
    pm2 save && env PATH=$PATH:/usr/bin pm2 startup systemd -u root --hp /root
    echo "TARGET 1 | IP: ${PRIVATE_IP} | Ports: 3306,5432,6379,8080,8888,9200,27017" > /var/log/target1.log

final_message: "Target 1 ready"
